// Generated by gencpp from file water/pathRequest.msg
// DO NOT EDIT!


#ifndef WATER_MESSAGE_PATHREQUEST_H
#define WATER_MESSAGE_PATHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace water
{
template <class ContainerAllocator>
struct pathRequest_
{
  typedef pathRequest_<ContainerAllocator> Type;

  pathRequest_()
    : goal_pose()  {
    }
  pathRequest_(const ContainerAllocator& _alloc)
    : goal_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _goal_pose_type;
  _goal_pose_type goal_pose;





  typedef boost::shared_ptr< ::water::pathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::water::pathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct pathRequest_

typedef ::water::pathRequest_<std::allocator<void> > pathRequest;

typedef boost::shared_ptr< ::water::pathRequest > pathRequestPtr;
typedef boost::shared_ptr< ::water::pathRequest const> pathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::water::pathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::water::pathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::water::pathRequest_<ContainerAllocator1> & lhs, const ::water::pathRequest_<ContainerAllocator2> & rhs)
{
  return lhs.goal_pose == rhs.goal_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::water::pathRequest_<ContainerAllocator1> & lhs, const ::water::pathRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace water

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::water::pathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::water::pathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::water::pathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::water::pathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::water::pathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::water::pathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::water::pathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6815aa242b5054bf4354bc4502009b6d";
  }

  static const char* value(const ::water::pathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6815aa242b5054bfULL;
  static const uint64_t static_value2 = 0x4354bc4502009b6dULL;
};

template<class ContainerAllocator>
struct DataType< ::water::pathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "water/pathRequest";
  }

  static const char* value(const ::water::pathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::water::pathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped goal_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::water::pathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::water::pathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::water::pathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::water::pathRequest_<ContainerAllocator>& v)
  {
    s << indent << "goal_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WATER_MESSAGE_PATHREQUEST_H
