// Generated by gencpp from file water/path.msg
// DO NOT EDIT!


#ifndef WATER_MESSAGE_PATH_H
#define WATER_MESSAGE_PATH_H

#include <ros/service_traits.h>


#include <water/pathRequest.h>
#include <water/pathResponse.h>


namespace water
{

struct path
{

typedef pathRequest Request;
typedef pathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct path
} // namespace water


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::water::path > {
  static const char* value()
  {
    return "85d15b4aaf93c7c5c72b84356966db40";
  }

  static const char* value(const ::water::path&) { return value(); }
};

template<>
struct DataType< ::water::path > {
  static const char* value()
  {
    return "water/path";
  }

  static const char* value(const ::water::path&) { return value(); }
};


// service_traits::MD5Sum< ::water::pathRequest> should match
// service_traits::MD5Sum< ::water::path >
template<>
struct MD5Sum< ::water::pathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::water::path >::value();
  }
  static const char* value(const ::water::pathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::water::pathRequest> should match
// service_traits::DataType< ::water::path >
template<>
struct DataType< ::water::pathRequest>
{
  static const char* value()
  {
    return DataType< ::water::path >::value();
  }
  static const char* value(const ::water::pathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::water::pathResponse> should match
// service_traits::MD5Sum< ::water::path >
template<>
struct MD5Sum< ::water::pathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::water::path >::value();
  }
  static const char* value(const ::water::pathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::water::pathResponse> should match
// service_traits::DataType< ::water::path >
template<>
struct DataType< ::water::pathResponse>
{
  static const char* value()
  {
    return DataType< ::water::path >::value();
  }
  static const char* value(const ::water::pathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WATER_MESSAGE_PATH_H
